---
auth:
  secret: test
users: # map with users
  user1: # username
    password: 96f49ad15aa185b68ab077300f8d226fbc36b0317ec2d7f088575f8255bc67da642e0aa0abc4e938dbc07f347296f69a291a3d7463e02112b94b2c06e1ce9108 # username+secret+password sha512 
    publicKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOwwY0kOSuDGBC2Y0rkCNWOteGh8qbGvrT516Np2BVDeUlDZG8jE6yodx3x4RI7SH3v0WX1nREMEWHwWURC/0nfZRRWMlOW8hrsFnacZFGPwGkrguCgZaE9hEkO8tHSdESyc1Y+ruKEDdNR9hm3F6VYrdkDylo0x0SH1Vizh9h/CX5IPJZKbO2FZOWq+gBbu0tKe/KtAZBUHZwygj0gGLwetjTZX/tMBY+5F3ZXi3n7OPG7Zo9O/vv3e03L33ixDPauOs8GPy22CE1IOMIN7VzYbgZI8fxZt1T1cEvfczjsaqwbhtcB7AsH3mlh232BR5Lsargdvj5sqnveHPkJqs9xpTxRgM1pxP6lwVw766Z2+PDTBKC776EqzDU5uYGvIFuN2tA5PxHIgFyWItKod2zcACjTkQcMxqKYcWAoNSwctNWVb+kHKLOIVGteg7OfRURf7kW01dR0fsgUKc7j9anX65U6uW6w9X+ZB0h7tHp1TALUy2+FksEWXDZod49GA8= 
    ips: # allowed cidrs
    - ::1/128
    - 127.0.0.1/32
    - 10.5.0.0/16
    - 1.1.1.1/32
    - fe80::/96
  user2: # username
    password: 9d9629200d759c761525080417da6a8b5f267e7a8851596b120237c05f00a313a2cd594eef51ba1f3205c24a1b521a0f6c53f5857e0526e395839986cb748605 # username+secret+password sha512 
    publicKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOwwY0kOSuDGBC2Y0rkCNWOteGh8qbGvrT516Np2BVDeUlDZG8jE6yodx3x4RI7SH3v0WX1nREMEWHwWURC/0nfZRRWMlOW8hrsFnacZFGPwGkrguCgZaE9hEkO8tHSdESyc1Y+ruKEDdNR9hm3F6VYrdkDylo0x0SH1Vizh9h/CX5IPJZKbO2FZOWq+gBbu0tKe/KtAZBUHZwygj0gGLwetjTZX/tMBY+5F3ZXi3n7OPG7Zo9O/vv3e03L33ixDPauOs8GPy22CE1IOMIN7VzYbgZI8fxZt1T1cEvfczjsaqwbhtcB7AsH3mlh232BR5Lsargdvj5sqnveHPkJqs9xpTxRgM1pxP6lwVw766Z2+PDTBKC776EqzDU5uYGvIFuN2tA5PxHIgFyWItKod2zcACjTkQcMxqKYcWAoNSwctNWVb+kHKLOIVGteg7OfRURf7kW01dR0fsgUKc7j9anX65U6uW6w9X+ZB0h7tHp1TALUy2+FksEWXDZod49GA8= 
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/TNO7s+Cy3swGSyuwFK0qYw37e7gtNSCGRIC2E3I0l271DfrwbRrNwQPRoT3p7xzDS0tT09ZD6Qch8vJthQw69MgsIr0cczjy8uJCNVeBrwefmHAPzObPZ4wYeEGphouhtJQLkWSeUoVcZaN2Gc9Q3AKS+CYMkjIA2ED0C+oJno2tpOIMEloNaLIbbReK3E+drqcgpti8vRaEDhn0gqBXYZkbPgwrW8WLsffTcdb3CwOD/Ria3ey0+m32ru0NseTBF4OuFa+ht2x5tCL8goICTl0L+ysEi5wXOkprAkSvFKe9Z18ibn+q4E4yx6x6yu2SomkSmLJAg5/9VsvDRSghPdWGuVlEygBTn5pyHw1nr6liblO4iHiGFFgogrAF7xQt0a5W3/NtIgMrq7MEsMqntoopwNbNcCD0/HdGN9tMnk/dtrs6Hbo1T5jAbc6dUBDgKr7FnyeQwPq3LeDkJ8WdzVY3kanvcgkz2xjAdrR2bv72P0HpmLxIVrcgqI9l3ds=
server: # server config
  listen: ":8081"  # default :8080 at http or 8443 on https 
  cert: example/server/server_cert.pem # server cert
  key: example/server/server_key.pem # server key
  clientcacert: example/clientCert1/ca.crt # trusted client ca
